### ISSUE TITLE
Lighthouse Grafana dashboard

### ISSUE THREAD

**Issue by muzammil84** [fedebertolini/lighthouse-graphite#1]
Hi Team,
i have followed instructions as per 
https://www.npmjs.com/package/lighthouse-graphite

and able to push the data on graphite (influxdb plugin) and i can see the data as well in database.
now my next query is to display same on grafana dashboard, how can i do that? is there any inbuilt dashboard available or i need to write my own?
i googled a lot about inbuilt but could not find one. please help. 
thank you.

**Comment by fedebertolini** [comment]
hi @muzammil84, sorry for the delay replying this, I'm not sure why I've never got a notification when you created the issue.
Not sure if relevant anymore, but in this post i'm explaining how to setup a CI to collect the lighthouse metrics and show them in grafana: https://medium.com/@fedebertolini/monitoring-your-websites-speed-for-free-94cb99e0a004

You could use this JSON as a template: https://github.com/fedebertolini/lighthouse-example-ci/blob/master/grafana-dashboard.json
